lib_libch_placement_la_SOURCES += \
 src/lookup3.c \
 src/ch-placement.c \
 src/SpookyV2.cpp \
 src/spooky.cpp \
 src/oid-gen.c

bin_PROGRAMS += \
 src/ch-placement-lookup \
 src/ch-placement-stripe \
 src/ch-placement-benchmark
